[package]
name = "static-server"
version = "0.1.0"
authors = ["Denis Kolodin <deniskolodin@gmail.com>"]

[dependencies]
log = "0.3.8"
futures = "0.1.14"
hyper = "0.11.2"

[dev-dependencies]
pretty_env_logger = "0.1.1"
